<a href="https://colab.research.google.com/github/mayargamal497/K-means/blob/master/K_meansIris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import packages

In [0]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt #Data Visualization 
from sklearn.cluster import KMeans #Kmeans Algo.
pd.set_option('display.max_columns', 30)

#Read Data

In [95]:
dataset = pd.read_csv('IRIS.csv', header=0)
dataset.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [96]:
dataset['species'][dataset['species'] == 'Iris-setosa'] = 0
dataset['species'][dataset['species'] == 'Iris-versicolor'] = 1
dataset['species'][dataset['species'] == 'Iris-virginica'] = 2

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doi

In [97]:
np.unique(dataset['species'])

array([0, 1, 2], dtype=object)

In [98]:
#Convert species to 
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

## Check dataset for NULL values or missing data

In [99]:
# dataset.isnull().any()
dataset.isnull().sum() 

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

## Visualized the data

In [0]:
#from random import randrange
#no_clusters=randrange(3,26)
#print(no_clusters)


## Initialize the parameters that we will be using

In [100]:
#def my_function11():
 no_clusters = int(input("Enter no. of clusters"))
 print (no_clusters)
 #return no_clusters

Enter no. of clusters6
6


## Kmeans

In [101]:
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values
kmeans = KMeans(n_clusters= no_clusters, n_init=1, random_state=1)
clustering_results = kmeans.fit_predict(X)
print('Done')

Done


In [102]:
clustering_results

array([4, 1, 1, 1, 4, 4, 1, 4, 1, 1, 4, 1, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4,
       1, 4, 1, 1, 4, 4, 4, 1, 1, 4, 4, 4, 1, 1, 4, 1, 1, 4, 4, 1, 1, 4,
       4, 1, 4, 1, 4, 1, 3, 3, 3, 2, 3, 2, 3, 2, 3, 2, 2, 2, 2, 3, 2, 3,
       2, 2, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 3, 2, 3, 3, 3,
       2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 0, 3, 5, 0, 0, 5, 2, 5, 0, 5,
       0, 0, 0, 3, 0, 0, 0, 5, 5, 3, 0, 3, 5, 3, 0, 5, 3, 3, 0, 5, 5, 5,
       0, 3, 3, 5, 0, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 0, 3], dtype=int32)

In [103]:
np.unique(clustering_results)

array([0, 1, 2, 3, 4, 5], dtype=int32)

In [0]:
# plt.scatter(X[clustering_results==0 , 0] , X[clustering_results==0,1] , c='red')
# plt.scatter(X[clustering_results==1 , 0] , X[clustering_results==1,1] , c='g')
# plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1], c='y',s=80)

In [105]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [0]:
dataset['CR'] = clustering_results

In [0]:
speciesR=[]
speciesR=dataset['species']
CRR=dataset['CR']

In [108]:
Xnew=kmeans.predict([[5.1, 3.5, 1.4, 0.2]])
Xnew

array([4], dtype=int32)

In [109]:
#def my_function2():
 print('***PREDICTION***') 
 for i in range(len([Xnew])):
  if speciesR[i]==0:
      print('Iris-setosa')
  elif speciesR[i]==1:
      print('Iris-versicolo')
  elif speciesR[i]==2:
      print('Iris-virginica') 

***PREDICTION***
Iris-setosa


In [110]:
print(dataset['species'].value_counts())

2    50
1    50
0    50
Name: species, dtype: int64


In [111]:
print(dataset['CR'].value_counts())

3    36
2    28
4    27
0    24
1    23
5    12
Name: CR, dtype: int64


In [112]:
 mayar=pd.crosstab(dataset['CR'], dataset['species'])
 mayar

species   0   1   2
CR                 
0         0   0  24
1        23   0   0
2         0  27   1
3         0  23  13
4        27   0   0
5         0   0  12

In [113]:
mayar['Total']= mayar.iloc[:,:].sum(axis=1)
mayar['Total']

CR
0    24
1    23
2    28
3    36
4    27
5    12
Name: Total, dtype: int64

In [114]:
mayar

species   0   1   2  Total
CR                        
0         0   0  24     24
1        23   0   0     23
2         0  27   1     28
3         0  23  13     36
4        27   0   0     27
5         0   0  12     12

In [115]:
df_new = mayar.loc[:,:].div(mayar['Total'], axis=0)
df_new

species    0         1         2  Total
CR                                     
0        0.0  0.000000  1.000000    1.0
1        1.0  0.000000  0.000000    1.0
2        0.0  0.964286  0.035714    1.0
3        0.0  0.638889  0.361111    1.0
4        1.0  0.000000  0.000000    1.0
5        0.0  0.000000  1.000000    1.0

In [116]:
 df_new.drop(columns=['Total'], inplace=True)
 df_new


species    0         1         2
CR                              
0        0.0  0.000000  1.000000
1        1.0  0.000000  0.000000
2        0.0  0.964286  0.035714
3        0.0  0.638889  0.361111
4        1.0  0.000000  0.000000
5        0.0  0.000000  1.000000

In [117]:
maxValue = df_new.max(axis=1)
print('Maximum value in each row : ')
print(maxValue)

Maximum value in each row : 
CR
0    1.000000
1    1.000000
2    0.964286
3    0.638889
4    1.000000
5    1.000000
dtype: float64


In [118]:
 print('***NEW CLUSTERS***')
 new=df_new.idxmax(axis=1)
 print(new)
 new

***NEW CLUSTERS***
CR
0    2
1    0
2    1
3    1
4    0
5    2
dtype: int64


CR
0    2
1    0
2    1
3    1
4    0
5    2
dtype: int64

In [0]:
crr=[]

In [0]:
crr=new

In [121]:
crr

CR
0    2
1    0
2    1
3    1
4    0
5    2
dtype: int64

In [122]:
for i in range(len(crr)):
    print(crr[i])

2
0
1
1
0
2


In [0]:
newCR = []

In [124]:
for i in dataset['CR']:
  if i <150:
    newCR.append(crr[i])
    

print(len(newCR))

150


In [0]:
dataset['newCR'] = newCR


In [126]:
dataset

sepal_length  sepal_width  petal_length  petal_width species  CR  newCR
0             5.1          3.5           1.4          0.2       0   4      0
1             4.9          3.0           1.4          0.2       0   1      0
2             4.7          3.2           1.3          0.2       0   1      0
3             4.6          3.1           1.5          0.2       0   1      0
4             5.0          3.6           1.4          0.2       0   4      0
..            ...          ...           ...          ...     ...  ..    ...
145           6.7          3.0           5.2          2.3       2   0      2
146           6.3          2.5           5.0          1.9       2   3      1
147           6.5          3.0           5.2          2.0       2   0      2
148           6.2          3.4           5.4          2.3       2   0      2
149           5.9          3.0           5.1          1.8       2   3      1

[150 rows x 7 columns]

In [127]:
movy=pd.crosstab(dataset['newCR'], dataset['species'])
movy

species   0   1   2
newCR              
0        50   0   0
1         0  50  14
2         0   0  36

In [128]:
 acc=pd.Series(np.diag(movy), index=[movy.index, movy.columns])
 print('***RIGHT PREDICTIONS***')
 print(acc)
 acc.sum()

***RIGHT PREDICTIONS***
newCR  species
0      0          50
1      1          50
2      2          36
dtype: int64


136

In [129]:
 #def my_function6():
  accuracy=acc.sum()/150
  print(accuracy)


0.9066666666666666


In [0]:
def function1():
  print('***NUMBER OF CLUSTERS***')
  print(no_clusters)

In [0]:
def function2():
  print('***PURITY***')
  print(df_new)

In [0]:
def function3():
  print('***ACCURACY***')
  print(accuracy)


In [0]:
def function4():
  function1()
  function2()
  function3()


In [134]:
function4()

***NUMBER OF CLUSTERS***
6
***PURITY***
species    0         1         2
CR                              
0        0.0  0.000000  1.000000
1        1.0  0.000000  0.000000
2        0.0  0.964286  0.035714
3        0.0  0.638889  0.361111
4        1.0  0.000000  0.000000
5        0.0  0.000000  1.000000
***ACCURACY***
0.9066666666666666


In [135]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species  CR  newCR
0           5.1          3.5           1.4          0.2       0   4      0
1           4.9          3.0           1.4          0.2       0   1      0
2           4.7          3.2           1.3          0.2       0   1      0
3           4.6          3.1           1.5          0.2       0   1      0
4           5.0          3.6           1.4          0.2       0   4      0

In [0]:
dataset_2 = dataset.copy(deep=True)